# Docker Compose for 4ex.ninja Development
version: '3.8'

services:
  # FastAPI Backend (Development)
  backend:
    build:
      context: ./4ex.ninja-backend
      dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=development
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=mongodb://mongodb:27017/4ex-ninja-dev
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./4ex.ninja-backend:/app:delegated
      - backend_node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - 4ex-dev-network

  # Next.js Frontend (Development)
  frontend:
    build:
      context: ./4ex.ninja-frontend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret
    ports:
      - "3000:3000"
    volumes:
      - ./4ex.ninja-frontend:/app:delegated
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - 4ex-dev-network

  # MongoDB Database (Development)
  mongodb:
    image: mongo:7-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=devpassword
      - MONGO_INITDB_DATABASE=4ex-ninja-dev
    volumes:
      - mongodb_dev_data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - 4ex-dev-network

  # Redis Cache (Development)
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - 4ex-dev-network

  # MongoDB Admin Interface (Development)
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=devpassword
      - ME_CONFIG_MONGODB_URL=mongodb://admin:devpassword@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - 4ex-dev-network

volumes:
  mongodb_dev_data:
  redis_dev_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  4ex-dev-network:
    driver: bridge
